### ISSUE TITLE
Specify list of input files and dest file

### ISSUE THREAD

**Issue by jfoliveira** [okaufmann/laravel-elixir-typescript#1]
Hi,
Thanks for keeping that extension alive! :-)
Most elixir `mixers` seem to follow the pattern of allowing specifying a list of input files as one of its parameters.
See for instance [LESS](https://github.com/laravel/elixir/blob/master/tasks/less.js) and [JavaScript](https://github.com/laravel/elixir/blob/master/tasks/scripts.js)

That is good, because you can have define different `packages` of scripts that could be used on a single page or on a list of pages instead of loading `app.js` in all pages.

Also, looking at the original repo where this one was froked from it seems this discussion was already happening there: https://github.com/MikeyAlder/laravel-elixir-typescript/issues/1

Is there any work in progress for allowing specifying a list of files?

Thanks!

**Comment by okaufmann** [comment]
Integrated in latest plugin version: https://github.com/okaufmann/laravel-elixir-typescript/releases/tag/v2.0.0
