### ISSUE TITLE
Compiling main file doesn't compile the imported files

### ISSUE THREAD

**Issue by hugobluefuse** [okaufmann/laravel-elixir-typescript#12]
I am using Angular 2 with Laravel (as most people nowadays are trying to :P) and currently, I have: 
mix.typescript( 'app/main.ts', 'public/app/' );

which bootstraps my whole app. But any import that main.ts does (like, app.component.ts) doesn't get compiled as well. 

Do I need to add mix.typescript to every file I import in order to compile the whole thing?

**Comment by okaufmann** [comment]
How does your import statements look like?

**Comment by hugobluefuse** [comment]
Hi,

I'm going to close the ticket because I'm not using elixir typescript anymore, so I won't be able to support the issue.
