### ISSUE TITLE
syntax error while compiling typescript code written in typescript 2

### ISSUE THREAD

**Issue by surjitkumar25** [okaufmann/laravel-elixir-typescript#13]

**Comment by okaufmann** [comment]
Please provide some logs or error messages and code samples.

**Comment by surjitkumar25** [comment]
http://prnt.sc/d20io1

**Comment by okaufmann** [comment]
As far as I can see is this not a Problem of this package. It uses the native typescript cli `tsc` and acts just as a wrapper. Did you try to compile your code by just run `tsc` in the directory where your tsconfig.json is located?

**Comment by surjitkumar25** [comment]
yes did that and it is getting compiled

**Comment by okaufmann** [comment]
I updated the internal used version of `gulp-typescript` to the latest one, so it should now use your installed version of typescript. Please try again with de latest version of this plugin.

**Comment by okaufmann** [comment]
Please reopen if error still occurs
