### ISSUE TITLE
Support for Laravel Elixir 5.4?

### ISSUE THREAD

**Issue by ghost** [okaufmann/laravel-elixir-typescript#16]
Are you planning to update this package in alignment with [Laravel 5.4](https://mattstauffer.co/blog/introducing-laravel-mix-new-in-laravel-5-4)?

**Comment by okaufmann** [comment]
This Plugin is just a adapter to use typescripts cli tsc to compile the ts files.

With Laravel 5.4 Elixir does not exists anymore. It was renamed to Laravel Mix and rewritten to webpack. Moreover it does no longer use gulp at all.
https://laravel-news.com/laravel-elixir-to-laravel-mix

If you want to use typescript with Laravel Mix use one of these Typescript loaders for webpack:
- https://github.com/s-panferov/awesome-typescript-loader
- https://github.com/TypeStrong/ts-loader

**Comment by ghost** [comment]
Guess not —  but thank you.
