### ISSUE TITLE
All ts files compiles to separate js files

### ISSUE THREAD

**Issue by denis-ionov** [okaufmann/laravel-elixir-typescript#19]
If pass array of files to .typescript() and provide output file (scripts.min.js), then each ts file compiles to separate js files, instead of one scripts.min.js. So, if we have something like this
`.typescript(['file1.ts', 'file2.ts', 'file3.ts'], 'public/js/scripts.min.js')`
we get `file1.js, file2.js, file3.js and scripts.min.js` in `public/js` folder.
How can i provide array of ts files, and build it to only one common minified js file, without generating multiple js files for each ts file?

**Comment by okaufmann** [comment]
You have to specify just one entry point. Something like `.typescript("entry-point.ts", "your/output/path/");`

Then in your entry-point.ts you should have something like this:

```ts
/// <reference path="file1.ts"/>
/// <reference path="file2.ts"/>
/// <reference path="file3.ts"/>

// or you use import or require
```

This package does not support input definition of multiple files.

**Comment by okaufmann** [comment]
SInce there was no response for several months I close this Issue. Please reopen if the problem does still exist.
