### ISSUE TITLE
Why it want outputFile in InputFolder ? 

### ISSUE THREAD

**Issue by Ortee** [okaufmann/laravel-elixir-typescript#6]
Fetching Typescript Source Files...
- resources/assets/typescript/app.js <-- Not Found
  typescript('app.js', 'public/')

When i add empty file app.js in typescript folder compilation is successful but public/ doesn't contain app.js

[`Stack`](http://stackoverflow.com/questions/35813939/laraver-5-angular-2-gulp-compile-typescript-app-js-not-found?noredirect=1#comment59296035_35813939)

**Comment by okaufmann** [comment]
Please try with latest rewrote version.
Reopen issue if error still occurs
