### ISSUE TITLE
ES5 won't compile

### ISSUE THREAD

**Issue by weilunsun** [okaufmann/laravel-elixir-typescript#7]
If i set the target to be ES5, I get multiple errors around ....Cannot find name \'Promise\'...
However, if I set the target to be ES6, everything compiles.

**Comment by riotCode** [comment]
Make sure typings.json and typings/ folder are in the same directory as the typescript files not root. This fixed the issue for me.

**Comment by moff** [comment]
@riotCode unfortunately that didn't help me and I still get the same error @weilunsun mentioned.
I use Angular 2.0.0-rc.4. 
I have **typings.json** and **typings/** folder right inside **/resources/assets/typescript** as you adviced.

**Comment by moff** [comment]
I have it fixed via adding this to a file where I boot the application:
`///<reference path="./typings/globals/es6-shim/index.d.ts"/>`

But I've read somewhere that it's a hack and shouldn't be used though. Anyway for now I haven't other solution.

If someone has a better understanding of this - please comment.

**Comment by okaufmann** [comment]
You should install typings through npm/yarn via @types/yourpackage either.
Please reopen if error still occurs
