### ISSUE TITLE
mix.typescript isn't reading the options

### ISSUE THREAD

**Issue by edaddou** [okaufmann/laravel-elixir-typescript#8]
Using angular 2 rc and Laravel, when I add this to the gulpfile 
`mix.typescript('**.ts','public/');` it works fine but there are certain things that won't work in angular
I tried to add the options this way:
`mix.typescript('**.ts','resources/views/app',{ "target": "es6","module": "commonjs","moduleResolution": "node","sourceMap": true,"emitDecoratorMetadata": true,"experimentalDecorators": true});`

I get this message in my terminal but nothing is compiled

> [16:57:26] Starting 'default'...
> [16:57:26] Starting 'typescript'...
> [16:57:26] Finished 'default' after 12 ms
> [16:57:26] Finished 'typescript' after 17 ms

**Comment by okaufmann** [comment]
I rewrite the whole Task into es6 and improved several lines, can you try it again with the latest version?
I also recommend you to use a tsconfig.json file, which should be placed in your project root.

**Comment by okaufmann** [comment]
Please reopen if error still occurs
